# Generated by Django 2.0.13 on 2019-12-02 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphabet',
            name='characters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), blank=True, null=True, size=None),
        ),
    ]
