# Generated by Django 2.0.13 on 2019-03-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='name',
            new_name='title',
        ),
    ]
