# Generated by Django 2.0.13 on 2019-12-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='characters_alpha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wordmeaning',
            name='source',
            field=models.TextField(blank=True, help_text='citation', null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='meanings',
            field=models.ManyToManyField(blank=True, to='gematriacore.LetterMeaning'),
        ),
    ]
