# Generated by Django 2.0.13 on 2019-03-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0002_auto_20190321_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='alphabet',
        ),
        migrations.AddField(
            model_name='letter',
            name='alphabet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gematriacore.Alphabet'),
        ),
    ]
