# Generated by Django 2.0.13 on 2019-12-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0002_auto_20191206_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordspelling',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='wordspelling',
            name='word',
        ),
        migrations.DeleteModel(
            name='WordSpelling',
        ),
    ]
