# Generated by Django 2.0.13 on 2019-12-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0002_alphabet_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alphabet',
            name='characters',
        ),
    ]
