# Generated by Django 2.0.13 on 2019-12-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0003_remove_alphabet_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gematriacore.Language'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_order',
            field=models.IntegerField(blank=True, help_text='The order from position 1 that this character appears in the alphabet.', null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='meanings',
            field=models.ManyToManyField(blank=True, null=True, to='gematriacore.LetterMeaning'),
        ),
    ]
