# Generated by Django 2.0.13 on 2019-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0003_auto_20190321_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='words',
            field=models.ManyToManyField(blank=True, to='gematriacore.Word'),
        ),
        migrations.AlterField(
            model_name='gematriamethod',
            name='letter_rules',
            field=models.ManyToManyField(blank=True, to='gematriacore.GematriaMethodLetterRule'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='meanings',
            field=models.ManyToManyField(blank=True, to='gematriacore.LetterMeaning'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='powers',
            field=models.ManyToManyField(blank=True, to='gematriacore.LetterPower'),
        ),
        migrations.AlterField(
            model_name='word',
            name='letters',
            field=models.ManyToManyField(blank=True, to='gematriacore.Letter'),
        ),
        migrations.AlterField(
            model_name='word',
            name='meanings',
            field=models.ManyToManyField(blank=True, to='gematriacore.WordMeaning'),
        ),
    ]
