# Generated by Django 2.0.13 on 2019-12-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0003_auto_20191211_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gematriamethodletterrule',
            options={'ordering': ['letter']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['language', 'name_original_language']},
        ),
    ]
