# Generated by Django 2.0.13 on 2019-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0004_auto_20191202_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordvalue',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
