# Generated by Django 2.0.13 on 2019-03-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0004_auto_20190321_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='meanings',
        ),
        migrations.RemoveField(
            model_name='word',
            name='meanings',
        ),
        migrations.AddField(
            model_name='lettermeaning',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gematriacore.Letter'),
        ),
        migrations.AddField(
            model_name='wordmeaning',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gematriacore.Word'),
        ),
    ]
