# Generated by Django 2.0.13 on 2019-12-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0004_auto_20191214_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['character', 'title', 'alphabet']},
        ),
    ]
