# Generated by Django 2.0.13 on 2019-03-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0005_auto_20190323_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='powers',
        ),
        migrations.AddField(
            model_name='letterpower',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gematriacore.Letter'),
        ),
    ]
