# Generated by Django 2.0.13 on 2019-12-05 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0005_auto_20191202_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
    ]
