# Generated by Django 2.0.13 on 2019-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0006_auto_20190323_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettermeaning',
            name='letter',
        ),
        migrations.AddField(
            model_name='letter',
            name='meanings',
            field=models.ManyToManyField(blank=True, to='gematriacore.LetterMeaning'),
        ),
    ]
