# Generated by Django 2.0.13 on 2019-12-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0006_auto_20191205_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='language',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='words',
        ),
        migrations.AlterField(
            model_name='letter',
            name='meanings',
            field=models.ManyToManyField(blank=True, null=True, to='gematriacore.LetterMeaning'),
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
    ]
