# Generated by Django 2.0.13 on 2019-03-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0007_auto_20190323_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lettermeaning',
            options={'ordering': ['meaning']},
        ),
        migrations.AddField(
            model_name='gematriamethodletterrule',
            name='gematria_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gematriacore.GematriaMethod'),
        ),
    ]
