# Generated by Django 2.0.13 on 2019-12-05 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0007_auto_20191205_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
