# Generated by Django 2.0.13 on 2019-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0009_remove_gematriamethod_letter_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['title', 'alphabet']},
        ),
        migrations.AlterModelOptions(
            name='letterpower',
            options={'ordering': ['power', 'letter']},
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_order',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
