# Generated by Django 2.0.13 on 2019-03-30 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0010_auto_20190323_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSpelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['letter_order', 'title', 'alphabet']},
        ),
        migrations.AlterModelManagers(
            name='word',
            managers=[
                ('related', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='letters',
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordspelling',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gematriacore.Letter'),
        ),
        migrations.AddField(
            model_name='word',
            name='spelling',
            field=models.ManyToManyField(blank=True, to='gematriacore.WordSpelling'),
        ),
    ]
