# Generated by Django 2.0.13 on 2019-03-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gematriacore', '0011_auto_20190330_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='spelling',
        ),
        migrations.AddField(
            model_name='wordspelling',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gematriacore.Word'),
        ),
    ]
